---
name: ansible-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN: ${{ secrets.AH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install collection dependencies
        run: ansible-galaxy collection install . -vvv

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
