---
name: Sanity tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]

jobs:
  sanity:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN: ${{ secrets.AH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install ansible-core
        run: python3 -m pip install ansible-core --disable-pip-version-check

      - name: Install collection dependencies
        run: ansible-galaxy collection install . -vvv

      - name: Build collection
        run: ansible-galaxy collection build

      - name: Install collection
        run: ansible-galaxy collection install ./f5networks-*.tar.gz --pre -p /home/runner/.ansible/collections

      - name: Run sanity tests
        run: ansible-test sanity --requirements --color --python 3.11
        working-directory: /home/runner/.ansible/collections/ansible_collections/f5networks/f5_infra_as_code_deployments
